spring:
      datasource:
        username: root
        password: root
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql:///openflatform?useUnicode=true&characterEncoding=utf8
        type: com.alibaba.druid.pool.DruidDataSource
